# Generated by Django 3.2.8 on 2021-10-29 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='address1',
        ),
        migrations.RemoveField(
            model_name='client',
            name='address2',
        ),
        migrations.RemoveField(
            model_name='client',
            name='contact_person',
        ),
        migrations.RemoveField(
            model_name='client',
            name='contact_reference',
        ),
        migrations.RemoveField(
            model_name='client',
            name='country',
        ),
        migrations.RemoveField(
            model_name='client',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='client',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='client',
            name='email',
        ),
        migrations.RemoveField(
            model_name='client',
            name='name',
        ),
        migrations.RemoveField(
            model_name='client',
            name='org_number',
        ),
        migrations.RemoveField(
            model_name='client',
            name='place',
        ),
        migrations.RemoveField(
            model_name='client',
            name='zipcode',
        ),
        migrations.AddField(
            model_name='client',
            name='numero',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='client',
            name='pergunta',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
