# Generated by Django 3.2.8 on 2021-10-29 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0004_auto_20211006_0957'),
        ('client', '0002_auto_20211029_1051'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Client',
            new_name='Perguntas',
        ),
    ]
